[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.0"
bevy_renet = "0.0.7"
serde = {version = "1", features = ["derive"]}
bincode = "1.3"
blitz-common = {path = "../blitz-common"}