[package]
name = "xtask"
version = "0.1.0"
edition = "2021"


[dependencies]
ctrlc = "3"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.42", features = ["Win32_Foundation", "Win32_System_Console"] } # sync with ctrlc version