[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "0.10.0", features = ["serialize"]}
bevy_renet = "0.0.7"
serde = {version = "1", features = ["derive"]}
bincode = "1.3"
blitz-common = {path = "../blitz-common"}